# Generated by Django 4.1.4 on 2023-03-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_category_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/img-not-found.png', null=True, upload_to='images/'),
        ),
    ]
